### ISSUE TITLE
如何去除中文的年月日

### ISSUE THREAD

**Issue by CoderWeiLee** [WangLiquan/EWDatePicker#1]

**Comment by WangLiquan** [comment]
func pickerView(_ pickerView: UIPickerView, titleForRow row: Int, forComponent component: Int) -> String? {
        if component == 0 {
            return "\((currentDateCom.year!) + row)\("年")"
        } else if component == 1 {
            return "\(row + 1)\("月")"
        } else {
            return "\(row + 1)\("日")"
        }
    }
把汉字去掉就好了啊

**Comment by CoderWeiLee** [comment]
哦哦 这是PickerView 的代理方法，好像使用UIDatePicker 没办法做到吧

**Comment by WangLiquan** [comment]
应该也可以，但是比较复杂，得不偿失啊。
